language: node_js
node_js:
  - "10.4.1"
before_script:
  - bash bin/server-setup.sh
cache:
  directories:
    - "node_modules"
sudo: required
services:
  - docker
after_success:
  - bin/docker-push.sh
  - bin/ews-deploy.sh