# Only run for develop and master branches
trigger:
- master
- develop

variables:
  imageName: 'eventregistration-eval'

pool:
  name: Hosted Ubuntu 1604

steps:
- task: UsePythonVersion@0
  displayName: 'Use Python 3.x'

# Change the image name when running on master 
- script: "echo '##vso[task.setvariable variable=imageName]eventregistration-prod'"
  condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'master'))

# Debug
# - script: "echo 'my name is $(imageName)'"

- task: Bash@3
  displayName: 'Install AWS CLI and other dependencies'
  inputs:
    targetType: 'inline'
    script: |
    pip3 install --upgrade pip
    sudo apt-get install -y python-setuptools jq
    pip install  awscli
    pip3 install awscli --upgrade

- task: Docker@0
  displayName: 'Build docker image'
  inputs:
    containerregistrytype: 'Container Registry'
    imageName: $(imageName)
    qualifyImageName: false
    includeLatestTag: true

- task: ECRPushImage@1
  displayName: 'Push docker image to AWS Container Registry'
  inputs:
    awsCredentials: 'AWS OTIK2'
    regionName: 'us-east-1'
    sourceImageName: $(imageName)
    repositoryName: eventregistration
    pushTag: develop

- task: AWSCLI@1
  displayName: 'Force a new deployment for the new docker image'
  inputs:
    awsCredentials: 'AWS OTIK2'
    regionName: 'us-east-1'
    awsCommand: ecs
    awsSubCommand: 'update-service'
    awsArguments: '--cluster ews-cluster --service $(imageName) --force-new-deployment'
    failOnStandardError: true
